version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cctv_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sistema20
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8500:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Sistema20@db:5432/cctv_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
